language: python
sudo: false
dist: trusty
cache: pip

env:
  - python: '2.7'
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson30
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson31
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson32
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson33
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson34
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson35
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson36
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson37
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson38
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson39
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson310
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson311
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson312
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson313
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson314
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson315
    - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson316

    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson30
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson31
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson32
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson33
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson34
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson35
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson36
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson37
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson38
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson39
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson310
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson311
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson312
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson313
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson314
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson315
    - TOXENV=.python27-sqlalchemy08-pyyaml302-simplejson316

  - python: '3.4'
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson30
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson31
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson32
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson33
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson34
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson35
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson36
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson37
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson38
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson39
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson310
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson311
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson312
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson313
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson314
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson315
    - TOXENV=.python34-sqlalchemy08-pyyaml301-simplejson316

    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson30
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson31
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson32
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson33
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson34
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson35
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson36
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson37
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson38
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson39
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson310
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson311
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson312
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson313
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson314
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson315
    - TOXENV=.python34-sqlalchemy08-pyyaml302-simplejson316
  - python: '3.5'
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson30
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson31
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson32
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson33
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson34
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson35
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson36
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson37
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson38
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson39
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson310
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson311
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson312
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson313
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson314
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson315
    - TOXENV=.python35-sqlalchemy08-pyyaml301-simplejson316

    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson30
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson31
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson32
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson33
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson34
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson35
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson36
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson37
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson38
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson39
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson310
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson311
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson312
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson313
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson314
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson315
    - TOXENV=.python35-sqlalchemy08-pyyaml302-simplejson316
  - python: '3.6'
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson30
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson31
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson32
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson33
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson34
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson35
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson36
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson37
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson38
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson39
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson310
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson311
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson312
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson313
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson314
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson315
    - TOXENV=.python36-sqlalchemy08-pyyaml301-simplejson316

    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson30
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson31
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson32
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson33
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson34
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson35
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson36
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson37
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson38
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson39
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson310
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson311
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson312
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson313
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson314
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson315
    - TOXENV=.python36-sqlalchemy08-pyyaml302-simplejson316
  - python: '3.6'
    - TOXENV=docs
  - python: '3.6'
    - TOXENV=coverage

install:
  - pip install -q tox-travis codecov

script:
  - tox

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
