language: python
sudo: false
dist: trusty
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x

matrix:
  include:
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson30
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson31
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson32
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson33
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson34
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson35
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson36
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson37
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson38
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson39
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson310
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson311
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson312
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson313
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson314
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson315
    - python: '2.7'
      env:
        - TOXENV=.python27-sqlalchemy08-pyyaml301-simplejson316
    - python: '3.4'
      env:
        - TOXENV=.python34
    - python: '3.5'
      env:
        - TOXENV=.python35
    - python: '3.6'
      env:
        - TOXENV=.python36
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=coverage

install:
  - pip install -U tox codecov

script:
  - tox -- -v

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
