language: python
sudo: false
dist: trusty
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

env:
  - SQLALCHEMY = "0.8"
  - SQLALCHEMY = "0.9"
  - SQLALCHEMY = "1.0"
  - SQLALCHEMY = "1.1"
  - SQLALCHEMY = "1.2"
  - PYYAML = "3.01"
  - PYYAML = "3.02"
  - PYYAML = "3.03"
  - PYYAML = "3.04"
  - PYYAML = "3.05"
  - PYYAML = "3.06"
  - PYYAML = "3.07"
  - PYYAML = "3.08"
  - PYYAML = "3.09"
  - PYYAML = "3.10"
  - PYYAML = "3.11"
  - PYYAML = "3.12"
  - PYYAML = "4.2b1"
  - PYYAML = "4.2b2"
  - SIMPLEJSON = "3.0"
  - SIMPLEJSON = "3.1"
  - SIMPLEJSON = "3.2"
  - SIMPLEJSON = "3.3"
  - SIMPLEJSON = "3.4"
  - SIMPLEJSON = "3.5"
  - SIMPLEJSON = "3.6"
  - SIMPLEJSON = "3.7"
  - SIMPLEJSON = "3.8"
  - SIMPLEJSON = "3.9"
  - SIMPLEJSON = "3.10"
  - SIMPLEJSON = "3.11"
  - SIMPLEJSON = "3.12"
  - SIMPLEJSON = "3.13"
  - SIMPLEJSON = "3.14"
  - SIMPLEJSON = "3.15"
  - SIMPLEJSON = "3.16"

install:
  - pip install -U tox-travis codecov

script:
  - tox

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
